language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
    env: PHPSTAN=1

script:
    - if [[ $PHPSTAN == "1" ]]; then
        composer phpstan;
      fi

before_script:
  - composer self-update
  - composer install
